name: poker-server
version: 0.1.0.0
github: "githubuser/poker-server"
license: Unlicense
author: "therewillbecode"
maintainer: "tomw08@gmail.com"
copyright: "2019 Tom Chambrier"

extra-source-files:
  - README.md
  - ChangeLog.md

description: A Poker Server Built With Haskell

dependencies:
  - base >= 4.12 && < 5
  - async
  - aeson
  - bytestring
  - hedis
  - ekg
  - containers
  - cryptohash
  - hashable
  - jose
  - persistent
  - persistent-postgresql
  - persistent-template
  - time
  - servant
  - servant-server
  - servant-auth
  - servant-auth-server
  - servant-auth-client
  - servant-foreign
  - servant-options
  - servant-websockets
  - pipes
  - pipes-aeson
  - pipes-concurrency
  - pipes-parse
  - transformers
  - random
  - text
  - wai
  - wai-extra
  - wai-logger
  - wai-cors
  - websockets
  - pretty-simple
  - utf8-string
  - split
  - stm
  - MonadRandom
  - monad-logger
  - mtl
  - jwt
  - listsafe
  - warp
  - lens
  - vector

library:
  source-dirs: src
  exposed-modules:
    - API
    - Bots
    - Database
    - Schema
    - Env
    - Types
    - Poker.Poker
    - Poker.Game.Actions
    - Poker.ActionValidation
    - Poker.Types
    - Poker.Game.Blinds
    - Poker.Game.Game
    - Poker.Game.Hands
    - Poker.Game.Utils
    - Poker.Game.Privacy
    - Socket
    - Socket.Table

executables:
  poker-server-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - poker-server

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - poker-server
      - hspec
      - hedgehog
      - hw-hspec-hedgehog
