// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Fetch = require("bs-fetch/src/Fetch.js");
var React = require("react");

function reducer(_prevState, action) {
  if (typeof action === "number") {
    return /* Loading */1;
  } else if (action.tag) {
    return /* Error */Block.__(0, [action[0]]);
  } else {
    return /* Loaded */Block.__(1, [action[0]]);
  }
}

function getProfile(param) {
  return fetch("/api/hello", Fetch.RequestInit[/* make */0](undefined, {
                      auth: "faketoken"
                    }, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (prim) {
                return prim.json();
              }));
}

function Counter(Props) {
  Props.className;
  var match = React.useReducer(reducer, /* NotLoading */0);
  var dispatch = match[1];
  React.useEffect((function () {
          Curry._1(dispatch, /* ProfileFetch */0);
          console.log("fetching");
          return undefined;
        }));
  return React.createElement("div", undefined, React.createElement("p", undefined, " get your profile"), React.createElement("button", {
                  onClick: (function (param) {
                      console.log("clicked");
                      return /* () */0;
                    })
                }, "Click me"));
}

var initialState = /* NotLoading */0;

var make = Counter;

exports.reducer = reducer;
exports.initialState = initialState;
exports.getProfile = getProfile;
exports.make = make;
/* react Not a pure module */
